version: "3.3"

services:
  ampvel:
    image: ampvel2:0.0.2
    build: ./ampvel2
    environment: 
      - HOST=192.168.0.42
      - PORT=4588
    networks:
      - ampvel2
    ports:
      - 4588:4588

networks:
  ampvel2:
